env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  no-cond-assign: 'off'
  accessor-pairs: error
  array-bracket-newline: 'off'
  array-bracket-spacing: 'off'
  array-callback-return: error
  array-element-newline: 'off'
  arrow-body-style: error
  arrow-parens: 'off'
  arrow-spacing:
    - error
    - after: true
      before: true
  block-scoped-var: error
  block-spacing:
    - error
    - always
  callback-return: error
  camelcase: 'off'
  capitalized-comments: 'off'
  class-methods-use-this: error
  comma-dangle: [error, never]
  comma-spacing: 
    - error
    - before: false
      after: true
  comma-style: [error, first]
  complexity: 'off'
  computed-property-spacing: 'off'
  consistent-return: 'off'
  consistent-this: error
  curly: 'off'
  default-case: error
  dot-location:
    - error
    - property
  dot-notation:
    - error
    - allowKeywords: true
  eol-last: error
  eqeqeq: 'off'
  for-direction: error
  func-call-spacing: error
  func-name-matching: error
  func-names: error
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  function-paren-newline: 'off'
  generator-star-spacing: error
  getter-return: error
  global-require: 'off'
  guard-for-in: error
  handle-callback-err: error
  id-blacklist: error
  id-length: 'off'
  id-match: error
  implicit-arrow-linebreak: 'off'
  indent: 'off'
  indent-legacy: 'off'
  init-declarations: 'off'
  jsx-quotes: error
  key-spacing: 'off'
  keyword-spacing: 'off'
  line-comment-position: 'off'
  linebreak-style: 'off'
  lines-around-comment: 'off'
  lines-around-directive: error
  lines-between-class-members: error
  max-depth: error
  max-len: 'off'
  max-lines: 'off'
  max-nested-callbacks: error
  max-params: error
  max-statements: 'off'
  max-statements-per-line: 'off'
  multiline-comment-style: 'off'
  multiline-ternary: error
  new-cap: error
  new-parens: error
  newline-after-var: 'off'
  newline-before-return: 'off'
  newline-per-chained-call: 'off'
  no-alert: error
  no-array-constructor: error
  no-await-in-loop: error
  no-bitwise: 'off'
  no-buffer-constructor: error
  no-caller: error
  no-catch-shadow: error
  no-confusing-arrow: error
  no-continue: error
  no-div-regex: error
  no-duplicate-imports: error
  no-else-return: error
  no-empty: [error, {allowEmptyCatch: true}]
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: error
  no-floating-decimal: error
  no-implicit-coercion: 
    - error
    - boolean: false
  no-implicit-globals: error
  no-implied-eval: error
  no-inline-comments: 'off'
  no-invalid-this: 'off'
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: 'off'
  no-lonely-if: error
  no-loop-func: error
  no-magic-numbers: 'off'
  no-mixed-operators: 'off'
  no-mixed-requires: error
  no-multi-assign: 'off'
  no-multi-spaces: 'off'
  no-multi-str: error
  no-multiple-empty-lines: error
  no-native-reassign: error
  no-negated-condition: error
  no-negated-in-lhs: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: 'off'
  no-path-concat: error
  no-plusplus: error
  no-process-env: 'off'
  no-process-exit: error
  no-proto: error
  no-prototype-builtins: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: 'off'
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: 'off'
  no-shadow-restricted-names: error
  no-spaced-func: error
  no-sync: 'off'
  no-tabs: error
  no-template-curly-in-string: error
  no-ternary: 'off'
  no-throw-literal: error
  no-trailing-spaces: error
  no-undef-init: error
  no-undefined: error
  no-underscore-dangle: error
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unused-expressions: [error,{ "allowTernary": true }]
  no-use-before-define: 'off'
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-rename: error
  no-useless-return: error
  no-var: error
  no-void: error
  no-warning-comments: error
  no-whitespace-before-property: error
  no-with: error
  nonblock-statement-body-position: error
  object-curly-newline: 'off'
  object-curly-spacing: 'off'
  object-property-newline: 'off'
  object-shorthand: error
  one-var: 'off'
  one-var-declaration-per-line: error
  operator-assignment:
    - error
    - always
  operator-linebreak:
    - error
    - before
    - overrides: { "=": "after" }
  padded-blocks: [error, never]
  padding-line-between-statements: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: warn
  prefer-numeric-literals: error
  prefer-promise-reject-errors: error
  prefer-reflect: 'off'
  prefer-rest-params: error
  prefer-spread: 'off'
  prefer-template: 'off'
  quote-props: 'off'
  quotes: 'off'
  radix: error
  require-await: error
  require-jsdoc: 'off'
  rest-spread-spacing: error
  semi: 'off'
  semi-spacing:
    - error
    - after: true
      before: false
  semi-style:
    - error
    - last
  sort-imports: error
  sort-keys: 'off'
  sort-vars: error
  space-before-blocks: error
  space-before-function-paren: [error, never]
  space-in-parens: 'off'
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: 'off'
  strict: error
  switch-colon-spacing: error
  symbol-description: error
  template-curly-spacing: error
  template-tag-spacing: error
  unicode-bom:
    - error
    - never
  valid-jsdoc: error
  vars-on-top: error
  wrap-iife: 'off'
  wrap-regex: 'off'
  yield-star-spacing: error
  yoda: 'off'
